backend:
  name: github
  repo: eslammedhat750-ai/Web
  branch: main

media_folder: "PNG"
public_folder: "PNG"

collections:
  - name: "data"
    label: "البيانات"
    files:
      - name: "products_list"
        label: "منتجات المتجر"
        file: "products.json"
        fields:
          - name: "products"
            label: "المنتجات"
            widget: "list"
            fields:
              - { label: "اسم الجهاز", name: "n", widget: "string" }
              - { label: "السعر", name: "p", widget: "number" }
              - { label: "القسم", name: "cat", widget: "string" }
              - { label: "وصف سريع", name: "desc", widget: "text" }
              - name: "imgs"
                label: "صور المنتج"
                widget: "list"
                field: { label: "اسم الصورة", name: "image_name", widget: "string" }
