backend:
  name: github
  repo: eslammedhat750-ai/Web
  branch: main
  site_domain: emmedical.shop
  display_url: https://emmedical.shop

local_backend: true
publish_mode: editorial_workflow

media_folder: "/"
public_folder: "/"

collections:
  - name: "products"
    label: "المنتجات"
    folder: "/"
    file: "products.json"
    extension: "json"
    format: "json"
    identifier_field: "n"
    create: true
    fields:
      - { label: "اسم المنتج", name: "n", widget: "string" }
      - { label: "السعر", name: "p", widget: "number" }
      - { label: "القسم", name: "cat", widget: "string" }
      - { label: "الوصف", name: "desc", widget: "text" }
      - { label: "صور المنتج", name: "imgs", widget: "list", field: { label: "صورة", name: "img", widget: "image" } }
