backend:
  name: git-gateway
  branch: main

media_folder: ""
public_folder: ""

collections:
  - name: "products"
    label: "قائمة المنتجات"
    files:
      - file: "products.json"
        label: "المنتجات"
        name: "products"
        fields:
          - label: "المنتجات"
            name: "products"
            label_singular: "منتج"
            widget: "list"
            fields:
              - {label: "اسم المنتج", name: "name", widget: "string"}
              - {label: "السعر", name: "price", widget: "string"}
              - {label: "صورة المنتج", name: "image", widget: "image"}
